version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: friendlyhello
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  counter:
    image: counter
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8008:8008"
    networks:
      - webnet
  redis:
    image: "redis:alpine"
#  db:
#    image: 
networks:
  webnet:
